### ISSUE TITLE
Add BOMs

### ISSUE THREAD

**Issue by arturo182** [koriwi/freedeck-hardware#10]
Appreciate the top and bottom images as well as the schematics, but I think a BOM is needed because it's hard to see if the passives are 0806 or 0603 :)

**Comment by koriwi** [comment]
after verifying the new pcb's, we will create a BOM

**Comment by koriwi** [comment]
the kicad files are online. you can export a BOM from them. i did it in Easy EDA (just zip the kicad file and import it in easy eda).
successfuly exported a bom and a pick and place file :)
