### ISSUE TITLE
Colour OLED screens?

### ISSUE THREAD

**Issue by hazrpg** [koriwi/freedeck-hardware#12]
I just saw your video on YouTube and loved this idea so much. Got me thinking, that I thought, how hard would it be to adapt it for colour OLED screens? Like these ones for example: https://www.ebay.co.uk/itm/0-95-Serial-UART-I2C-SPI-65K-Color-OLED-96x64-Display-Module-for-Arduino-PIC/372240899300?hash=item56ab495ce4:g:7twAAOSwy1VZsJjL

**Comment by koriwi** [comment]
that would be 90$ just for the displays (if you buy them from your link)

**Comment by kfpv** [comment]
I had a similar idea but these LCD screens would be MUCH cheaper than oleds. https://www.aliexpress.com/item/32918394604.html

**Comment by koriwi** [comment]
please reopen if you have more information and check out #16
