### ISSUE TITLE
SMD BOM

### ISSUE THREAD

**Issue by apuerto11** [koriwi/freedeck-hardware#14]
Hi, is it possible to get a BOM for the SMD version of the board?

**Comment by carlfugate** [comment]
I'm looking for the SMD BOM as well.

**Comment by koriwi** [comment]
from the easyeda, kicad files, you can export a BOM :)

**Comment by carlfugate** [comment]
Thanks @koriwi.  Here is an export.
[BOM_FreeDeck 2020-02_2020-07-24_13-12-55.pdf](https://github.com/koriwi/freedeck-hardware/files/4973641/BOM_FreeDeck.2020-02_2020-07-24_13-12-55.pdf)
