### ISSUE TITLE
Using colour LCD screens?

### ISSUE THREAD

**Issue by kfpv** [koriwi/freedeck-hardware#16]
https://www.aliexpress.com/item/32918394604.html
These screens cost about the same but they can display colours. Would it be possible to use them instead?

**Comment by koriwi** [comment]
i think the arduino does not have enough horsepower to refresh colored screens fast enough.
feel free to reopen the issue if you have more information :)

**Comment by seanspotatobusiness** [comment]
What about the stm32f103c8t6 (aka blue pill) - does that not have enough processing power?
