### ISSUE TITLE
Nothing displayed on screen

### ISSUE THREAD

**Issue by HarsiFPV** [koriwi/freedeck-hardware#23]
Using all the components listed, I finished building it and when I plug it in after puting in the SD card containing the config file, the screens light up bright but do not display any image contained in the SD card. Using the serial function in the configurator doesn't help.
If you have any idea of what could be causing the issue feel free to tell me.
Thanks :)

**Comment by Gregor-Davies** [comment]
Hey!
It would be helpful if you provided a picture of your wiring to make sure everything is connected properly.

**Comment by HarsiFPV** [comment]
Hey ! My bad for not saying this but I am using the pcb that Adam Welch provides in his video. [
![IMG_20210323_205329](https://user-images.githubusercontent.com/81262068/112209796-29027f80-8c1a-11eb-9d7b-8dd7e3d15dc5.jpg)
![IMG_20210323_205324](https://user-images.githubusercontent.com/81262068/112209813-2f90f700-8c1a-11eb-8c43-9c7f9331c54c.jpg)

](url)

**Comment by Gregor-Davies** [comment]
Did/does the Arduino work when not attached to the pcb? The pins on the Arduino might need a bit more solder.

**Comment by HarsiFPV** [comment]
Yes I flashed the arduino with the sketch before soldering it. I will try to add a little bit more solder. I'll keep you in touch thanks :)

**Comment by HarsiFPV** [comment]
So I wen't ahead and reflowed solder on every pin of the board, and I am still facing the same issue :(

**Comment by Gregor-Davies** [comment]
In that case there's something wrong in the pcb try going around on the pcb with a multimeter.

**Comment by legomannetje** [comment]
Hey HarsiFPV,

If you still have this issue, please visit our discord! [Click here to join](https://discord.gg/sEt2Rrd)

**Comment by koriwi** [comment]
Feel free to reopen or comment your solution. will close this ticket now :)
