### ISSUE TITLE
changing shift registers to smd in TH PCB.

### ISSUE THREAD

**Issue by LordSexy** [koriwi/freedeck-hardware#28]
Can somebody help me to fix a single issue?
I ordered smd shift registers and I'd like to order new PCBs with only the shift register changed to the smd format. 
Im used to work in easyeda, so if I need new software  please leave you suggestion....
As a highschool student I used also Sprint Layout, but I dont have the SPECIFIC version of that programm anymore.

When Im done I can open a pull request, if you wish to have that in the main branch.

Sorry if the "issue" page is not the right place to take part in this discussion.
Cheers,
Lord

**Comment by koriwi** [comment]
hey @LordSexy 
to get some interactive help you should visit our discord. we have a few people there who could guide you through this process :)
