### ISSUE TITLE
rough technical drawing

### ISSUE THREAD

**Issue by hanswurstgmbh** [koriwi/freedeck-hardware#4]
It would be nice to have a rough sketch with the distances drawn on it. So a simple rough sketch similar to a technical drawing. So we could create a rough design for a housing in a cad software to be able to print it later directly in 3d.

Thanks!

**Comment by koriwi** [comment]
https://github.com/koriwi/freedeck-hardware/blob/master/3x2/pcb/pdf/freedeck%203x2_etch_silk_top.pdf

**Comment by koriwi** [comment]
https://github.com/koriwi/freedeck-hardware/blob/master/3x2/pcb/pdf/freedeck%203x2_etch_silk_bottom_mirror.pdf

**Comment by koriwi** [comment]
these should be enough :)

**Comment by koriwi** [comment]
https://github.com/koriwi/freedeck-hardware/pull/6

**Comment by koriwi** [comment]
https://github.com/koriwi/freedeck-hardware/tree/master/3x2/3d/step

**Comment by hanswurstgmbh** [comment]
i could not open the stp file and the pdfs do not have the distances, so it will be difficult to make something. 
But the case you designed is already very nice

**Comment by koriwi** [comment]
tested it in this online viewer and it works fine.
https://www.emachineshop.com/free-online-step-file-viewer/
you can use the pdf and scale it by the holes in the pcb. one hole is 1/10th of and inch
thank you. i ordered pcb at jlcpcb. when they arrive i will print the case and test the fit.
when the pcb arrive, tell me where you live and i will send you one.
